CREATE TABLE PRODUCT_PRICES (
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST BIGINT,
    PRODUCT_ID BIGINT,
    PRIORITY INT,
    PRICE NUMERIC(20, 2),
    CURRENCY VARCHAR(40)
);