CREATE TABLE PRODUCT_PRICES (
    PRODUCT_PRICE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE NUMERIC(20, 2) NOT NULL,
    CURRENCY VARCHAR(4) NOT NULL
);

CREATE INDEX idx_prices_query_optimization ON PRODUCT_PRICES (product_id, brand_id, priority, start_date, end_date);